### ISSUE TITLE
KeyError: 'gpt_bigcode' 

### ISSUE THREAD

**Issue by Symbolk** [bigcode-project/starcoder#5]
Hi, I am trying to run the given inference code in the README, but it gives me such error after downloading the files:

```
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████| 677/677 [00:00<00:00, 44.4kB/s]
Downloading (…)olve/main/vocab.json: 100%|████████████████████████████████████████████████████████████| 777k/777k [00:00<00:00, 1.02MB/s]                                                                                                                                            
Downloading (…)olve/main/merges.txt: 100%|█████████████████████████████████████████████████████████████| 442k/442k [00:00<00:00, 774kB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████████████████████████████████████████████████████| 2.06M/2.06M [00:00<00:00, 2.09MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████| 532/532 [00:00<00:00, 99.9kB/s]
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████| 1.04k/1.04k [00:00<00:00, 271kB/s]
Traceback (most recent call last):                                   
  File "/home/workspace//starcoder/starcoder.py", line 7, in <module>                                                               
    model = AutoModelForCausalLM.from_pretrained(checkpoint, trust_remote_code=True).to(device)
  File "/root/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(                     
  File "/root/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 917, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]         
  File "/root/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 623, in __getitem__
    raise KeyError(key)                                              
KeyError: 'gpt_bigcode' 
```

**Comment by widdakay** [comment]
I got this issue and was able to fix it by updating my copy of `transfomers` with `pip install -U transformers`.

**Comment by better629** [comment]
use the latest `transformers` source code and `pip3 install -e .`. 
the latest version is `transformers-4.29.0.dev0`

**Comment by loubnabnl** [comment]
indeed it seems you are using an old version, the `gpt_bigcode` architecture was introduced in `transformers 4.28.1`

**Comment by Symbolk** [comment]
Thanks! Upgrading to >4.28.1 solves it.

**Comment by noobmldude** [comment]
Thanks! 
Resolved this issue with an upgrade of `transfomers` package.

**Comment by Yamijalaa** [comment]
I updated it but still facing the same error

**Comment by chenhong1875435468** [comment]
I've faced the same problem, but I tried uninstall transformer and download the lates one, the problem then get solved
