### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'prompt_type'

### ISSUE THREAD

**Issue by phalexo** [bigcode-project/starcoder#69]
======================

=== EXAMPLE 6 ===

<|system|>
<|end|>
<|user|>
Implement a program to find the common elements in two arrays without using any extra data structures.<|end|>
<|assistant|>
You can use Python's built-in set datatype for this problem. You may also want to try out collections.Counter, which is similar but not quite as useful here (but it does have some nice features). <|end|>
"""

<|endoftext|>

======================

Traceback (most recent call last):
  File "/home/developer/starcoder/chat/generate.py", line 139, in <module>
    main()
  File "/home/developer/starcoder/chat/generate.py", line 130, in main
    model_name = f"{raw_model_name}-{args.prompt_type}"
AttributeError: 'Namespace' object has no attribute 'prompt_type'
(StarCoder) developer@ai:~/starcoder/chat$

**Comment by phalexo** [comment]
p.s. It is NOT actually implementing anything. It is simply dishing out useless advice to do it yourself.
