### ISSUE TITLE
DeepSpeed+LoRA got RuntimeError: expected there to be only one unique element in <generator object Init._convert_to_deepspeed_param.<locals>.all_gather_coalesced.<locals>.<genexpr> at 0x7f2ec8daf900>

### ISSUE THREAD

**Issue by LaniakeaS** [bigcode-project/starcoder#96]
**system info**
Linux 20.04
RTX 3090 *8

---

**launch command**
```bash
deepspeed finetune/finetune_lora.py \
--model_path="/home/guest/models/starcoder" \
--dataset_path="finetune/data/leetcode_instructions.jsonl" \
--subset="finetune/data/leetcode_instructions.jsonl" \
--split="train" \
--size_valid_set=3000 \
--streaming \
--seq_length=2048 \
--max_steps=1000 \
--batch_size=1 \
--input_column_name="input" \
--output_column_name="output" \
--gradient_accumulation_steps=1 \
--learning_rate=1e-4 \
--lr_scheduler_type="cosine" \
--num_warmup_steps=100 \
--weight_decay=0.05 \
--output_dir="./checkpoints"
```

---

**code diff**
```python
def run_training(args, train_data, val_data):
    print("Loading the model")
    # disable caching mechanism when using gradient checkpointing
    print(int(os.getenv('LOCAL_RANK')))
    model = AutoModelForCausalLM.from_pretrained(
        args.model_path,
        # use_auth_token=True,
        # use_cache=not args.no_gradient_checkpointing,
        load_in_8bit=True,
        device_map={'': int(os.getenv('LOCAL_RANK'))}
        # device_map={"": accelerator.process_index}
    )
    print('got model')

    print('preparing for 8bit')
    model = prepare_model_for_int8_training(model)
    print('prepared')

    lora_config = LoraConfig(  # Lora 的训练参数
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules = ["c_proj", "c_attn", "q_attn"]
    )

    print('getting lora')
    model = get_peft_model(model, lora_config)
    print('got lora')

    print_trainable_parameters(model)
```

---

**exception traceback**
```
Traceback (most recent call last):
  File "/home/guest/starcoder/finetune/finetune_lora_ds.py", line 414, in <module>
    main(args)
  File "/home/guest/starcoder/finetune/finetune_lora_ds.py", line 403, in main
    run_training(args, train_dataset, eval_dataset)
  File "/home/guest/starcoder/finetune/finetune_lora_ds.py", line 379, in run_training
    trainer.train()
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/trainer.py", line 2699, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/trainer.py", line 2731, in compute_loss
    outputs = model(**inputs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1735, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/peft/peft_model.py", line 530, in forward
    return self.base_model(
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 808, in forward
    transformer_outputs = self.transformer(
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 663, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 659, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 316, in forward
    attn_outputs = self.attn(
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py", line 230, in forward
    query, key_value = self.c_attn(hidden_states).split((self.embed_dim, 2 * self.kv_dim), dim=2)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 371, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 483, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 254, in fetch_sub_module
    self.__all_gather_params(params_to_fetch)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 386, in __all_gather_params
    handle = partitioned_params[0].all_gather_coalesced(partitioned_params)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 942, in all_gather_coalesced
    dtype=get_only_unique_item(p.dtype for p in params),
  File "/home/guest/miniconda3/envs/starcoder/lib/python3.9/site-packages/deepspeed/runtime/utils.py", line 824, in get_only_unique_item
    raise RuntimeError(f"expected there to be only one unique element in {items}")
RuntimeError: expected there to be only one unique element in <generator object Init._convert_to_deepspeed_param.<locals>.all_gather_coalesced.<locals>.<genexpr> at 0x7f2ec8daf900>
```

**Comment by LaniakeaS** [comment]
just found this [https://github.com/Facico/Chinese-Vicuna/issues/205](url). already set load_in_8bit to default, but got OOM from CUDA. Why ZeRO-3 doesn't work?

**Comment by leoluopy** [comment]
@LaniakeaS 
hi, have you solved this issue , i met the same error with you . could you share the solution ？  if you have the answer .

**Comment by LaniakeaS** [comment]
> @LaniakeaS
> hi, have you solved this issue , i met the same error with you . could you share the solution ？ if you have the answer .

don't use `load_in_8bit` argument in `from_pretrained` function.

for OOM problem, well..... it's been 2 months, i've forgotten how I solved this problem.😂

**Comment by LaniakeaS** [comment]
> @LaniakeaS
> hi, have you solved this issue , i met the same error with you . could you share the solution ？ if you have the answer .

Oh, i remember i solved this problem by initializing `TraningArguments` before using `from_pretrained` function, which found by [official HuggingFace documentation](https://huggingface.co/docs/transformers/main_classes/deepspeed#constructing-massive-models).

**Comment by leoluopy** [comment]
@LaniakeaS
thanks for reply . and what do you mean about  initializing TraningArguments before using from_pretrained . 
can you share some pseudo code ?

**Comment by LaniakeaS** [comment]
@leoluopy 
just like this.
```python
training_args = TrainingArguments(...)
tokenizer = AutoTokenizer.from_pretrained(...)
model = AutoModelForCausalLM.from_pretrained(...)
trainer = Trainer(args=training_args, ...)
trainer.train()
```
If you are using ZeRO-3, then initializing of TraningArguments before loading model, which can trigger `zero.init()` before loading that can load your massive model on different GPUs, which can try to avoid OOM.

**Comment by LaniakeaS** [comment]
> @leoluopy just like this.
> 
> ```python
> training_args = TrainingArguments(...)
> tokenizer = AutoTokenizer.from_pretrained(...)
> model = AutoModelForCausalLM.from_pretrained(...)
> trainer = Trainer(args=training_args, ...)
> trainer.train()
> ```
> 
> If you are using ZeRO-3, then initializing of TraningArguments before loading model, which can trigger `zero.init()` before loading that can load your massive model on different GPUs, which can try to avoid OOM.

remember add deepspeed argument in it, like below.
```python
TrainingArguments(deepspeed='path of config file', ...)
```
